# Algorithm Optimization problems

## Exercise 1

Suppose a manager gives a task to two of his employees to design an algorithm in Python that efficiently compute sums of diagonals of a matrix.

For example:

```py
Input : 


1 2 3 4
4 3 2 1
7 8 9 6
6 5 4 3

Output :

Principal Diagonal: 16
Secondary Diagonal: 20
```

The primary diagonal is formed by the elements 1,3,9,3. 
 

Condition for Principal Diagonal: The row-column condition is row = column. 

The secondary diagonal is formed by the elements 4,2,8,6.

Condition for Secondary Diagonal: The row-column condition is row = number Of Rows – column -1.

The algorithm developed by the first employee looks like this:

**Method 1:**

In this method, he used two loops. A loop for columns and a loop for rows and in the inner loop we check for the condition stated above.

In [1]:
# A simple Python program to find sum of diagonals

MAX = 100
 
def DiagonalSums_emp1(mat, n):
 
    principal = 0
    secondary = 0;
    for i in range(0, n):
        for j in range(0, n):
 
            # Condition for principal diagonal
            if (i == j):
                principal += mat[i][j]
 
            # Condition for secondary diagonal
            if ((i + j) == (n - 1)):
                secondary += mat[i][j]
                
    print("Principal Diagonal:", principal)
    print("Secondary Diagonal:", secondary)
 

a = [[ 1, 2, 3, 4 ],
     [ 5, 6, 7, 8 ],
     [ 1, 2, 3, 4 ],
     [ 5, 6, 7, 8 ]]

DiagonalSums_emp1(a, 4)
 
# This code is contributed
# by ihritik

Principal Diagonal: 18
Secondary Diagonal: 18


The algorithm developed by the second employee looks like this:

**Method 2:**

In this method we use one loop. A loop for calculating sum of both the principal and secondary diagonals: 

In [2]:
# A simple Python3 program to find sum of diagonals
MAX = 100
 
def DiagonalSums_emp2(mat, n):
 
    principal = 0
    secondary = 0
    for i in range(0, n):
        principal += mat[i][i]
        secondary += mat[i][n - i - 1]
         
    print("Principal Diagonal:", principal)
    print("Secondary Diagonal:", secondary)
 

a = [[ 1, 2, 3, 4 ],
     [ 5, 6, 7, 8 ],
     [ 1, 2, 3, 4 ],
     [ 5, 6, 7, 8 ]]

DiagonalSums_emp2(a, 4)
 
# This code is contributed
# by ihritik

Principal Diagonal: 18
Secondary Diagonal: 18



The manager has to decide which algorithm to use. To do so, he has to find the complexity of the algorithm. A good algorithm doesn't only find an answer, it finds it quickly and efficiently. But how do we evaluate how fast an algorithm is? One way to do so is by finding the time required to execute the algorithms. We can measure

The %time command times a single run of a function. Here is an example on how it is used:

```py
In [3]: %time sum(range(100000))
CPU times: user 2.68 ms, sys: 3 µs, total: 2.68 ms
Wall time: 2.69 ms
Out[3]: 4999950000
```

We can also use the time library:

```py
import time

start = time.time()
# your code
# end
print(f'Time: {time.time() - start}')
```

**Find the time required to execute each of the algorithms**

In [ ]:
#YOUR CODE HERE TO FIND THE TIME REQUIRED TO EXECUTE ALGORITHM BUILT BY THE FIRST EMPLOYEE

In [ ]:
#YOUR CODE HERE TO FIND THE TIME REQUIRED TO EXECUTE ALGORITHM BUILT BY THE SECOND EMPLOYEE

However, execution time is not a good metric to measure the complexity of an algorithm since it depends upon the hardware. A more objective complexity analysis metrics for the algorithms is needed. This is where Big O notation comes to play.

As we already know, the complexity of an algorithm is said to :

Constant if:

The steps required to complete the execution of an algorithm remain constant, irrespective of the number of inputs. The constant complexity is denoted by O(c) where c can be any constant number.

Linear if:

The steps required to complete the execution of an algorithm increase or decrease linearly with the number of inputs. Linear complexity is denoted by O(n). For instance, if there are 4 inputs in the inputs list, the for-loop will be executed 4 times, and so on.

Quadratic if:

The steps required to execute an algorithm are a quadratic function of the number of items in the input. Quadratic complexity is denoted as O(n^2). The total number of steps performed is n * n, where n is the number of items in the input array.

**Find out the complexity of each algorithm in Big O Notation and draw a line plot with the varying size of the items input on the x-axis and the number of steps on the y-axis.**

In [ ]:
# Write the time complexity in Big O notation for the first employee's algorithm.
# CODE HERE TO MAKE A PLOT FOR THE FIRST EMPLOYEE'S SOLUTION

In [ ]:
# Write the time complexity in Big O notation for the second employee's algorithm
# CODE HERE TO MAKE A PLOT FOR THE SECOND EMPLOYEE'S SOLUTION

## Exercise 2 : Selection Sort algorithm


### Theory:

The selection sort algorithm sorts an array by repeatedly finding the minimum element (considering ascending order) from unsorted part and putting it at the beginning. The algorithm maintains two subarrays in a given array:

-The subarray which is already sorted. 

-Remaining subarray which is unsorted.

In every iteration of selection sort, the minimum element (considering ascending order) from the unsorted subarray is picked and moved to the sorted subarray. 

Lets consider the following array as an example: 
```py
arr[] = {64, 25, 12, 22, 11}
```
\
**First pass:**

For the first position in the sorted array, the whole array is traversed from index 0 to 4 sequentially. The first position where 64 is stored presently, after traversing whole array it is clear that 11 is the lowest value.
```py
[64  25  12  22  11]
```

Thus, replace 64 with 11. After one iteration 11, which happens to be the least value in the array, tends to appear in the first position of the sorted list.
```py
[11  25  12  22  64]
```
\
**Second Pass:**

For the second position, where 25 is present, again traverse the rest of the array in a sequential manner.
```py
[11  25  12  22  64]
```

After traversing, we found that 12 is the second lowest value in the array and it should appear at the second place in the array, thus swap these values.
```py
[11  12  25  22  64]
```
\
**Third Pass:**

Now, for third place, where 25 is present again traverse the rest of the array and find the third least value present in the array.
```py
[11  12  25  22  64]
```

While traversing, 22 came out to be the third least value and it should appear at the third place in the array, thus swap 22 with element present at third position.
```py
[11  12  22  25  64]
```
\
**Fourth pass:**

Similarly, for fourth position traverse the rest of the array and find the fourth least element in the array 
As 25 is the 4th lowest value hence, it will place at the fourth position.

```py
[11  12  22  25  64]  
```
\
**Fifth Pass:**

At last the largest value present in the array automatically get placed at the last position in the array
The resulted array is the sorted array.

```py
[11  12  22  25  64] 
```



### Problem:


**Part 1: Create a python program for implementation of Selection Sort**

Given the following unsorted array, create a python program to implement selection sort:
```py
arr[] = {10,5,3,8,9,4}
```
\
Instructions:

-Initialize minimum value(min_idx) to location 0

-Traverse the array to find the minimum element in the array

-While traversing if any element smaller than min_idx is found then swap both the values.

-Then, increment min_idx to point to next element

-Repeat until array is sorted

\
**Part 2: Time Complexity Analysis of Selection Sort**


How many nested loops are there?

What is the overall time complexity?



In [ ]:

# Python program for implementation of Selection Sort

import sys

A = [10,5,3,8,9,4]
 
# Traverse through all array elements

     
    # Find the minimum element in remaining
    # unsorted array
    




    # Swap the found minimum element with
    # the first element       
   
 
# Driver code to test above
print ("Sorted array")
# Traverse through all array elements:
    print("%d" %A[i],end=" ")

## Exercise 3: Implementing a KNN Algorithm with Scikit-learn

In this exercise, we will have a brief introduction to the Scikit-learn library. We will see how this library can be used to implement the KNN algorithm in less than 20 lines of code.  Then the task will be to try to optimize the parameter of this algorithm. Don't worry! Scikit-Learn, and also de KNN algorithm will be explained very well in future modules.

**The dataset**

We are going to use the famous iris data set for our KNN example. The dataset consists of four attributes: sepal-width, sepal-length, petal-width and petal-length. These are the attributes of specific types of iris plant. The goal is to predict the class to which these plants belong. There are three classes in the dataset: Iris-setosa, Iris-versicolor and Iris-virginica.


**Library installation**


First let's install the Scikit-learn library by entering the following command in the terminal:

```py
pip install -U scikit-learn
```

Now let's see how to implement the KNN algorithm:

**Importing libraries**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing and loading the dataset**

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

**Looking at the first rows of the data**

In [ ]:
dataset.head()

**Pre-processing**

Split dataset into attributes and labels. Again, don't worry, this data preprocessing part will also be very well explained in a future module. Now, we will focus on the algorithm optimization.

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

**Train Test split**

In machine learning, when we are building a model, we have to be careful to do not overfit it. Overfitting means that our model works very well in known data but when it works with unseen data, it has a poor performance. To avoid this, we divide our dataset into training and test datasets. This way our algorithm is tested on un-seen data to evaluate the performance of our algorithm. We will divide it into 80% training data and 20% for testing. This 4 blocks of data would be:

-X_train: training features

-X_test: test features

-y_train: training labels

-y_test: test labels

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

**Feature Scaling**

The majority of classifiers calculate the distance between two points by the Euclidean distance. If one of the features has a broad range of values, the distance will be governed by this particular feature. Therefore, the range of all features should be normalized so that each feature contributes approximately proportionately to the final distance.

It is a good practice to scale the features so that all of them can be uniformly evaluated.
We will read more about feature scaling in the data preprocessing module, but now, let's have a first look at how it is implemented.

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

**Train the KNN algorithm**

Now our data is ready for training. We will begin by importing the algorithm we want to train from the scikit-learn library, and then we will initialize it with one parameter: n_neigbours. This is basically the value for 'K'. We don't know what is the ideal number of neighbors(K) yet so we will start it with 5. After making the predictions we will try to otpimize this K value.

Finally, we train our model using .fit on our training features and training labels (they both represent 80% of the data).

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

**Make predictions on our test data**

The model has been trained, so now we use the same algorithm (stored in the 'classifier' variable)  to predict only on the features of the test dataset (20% of the data). This time we don't use the labels, because we want to predict them, and then compare them with the real test labels.

In [ ]:
y_pred = classifier.predict(X_test)

**Evaluate the algorithm**

Confusion matrix, precision, recall and f1 score are the most commonly used evaluation metrics for classification problems.
The confusion_matrix and classification_report methods of the sklearn.metrics can be used to calculate these metrics. Here we will compare our y_pred results versus our y_test true labels.

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

**Optimizing the KNN algorithm**

There is no way to know beforehand which value of 'K' yields the best results since the beginning. We randomly chose 5 as the 'K' value.

This is where we optimize our algorithm. To help find the best value of K:

1. First create a function that calculates the mean of error for all the predicted values where K ranges from 1 to 40. 
2. Plot the error values against K values.
3. Vary the test and training size along with the K value to see how your results differ and how can you improve the accuracy of your algorithm. 



In [ ]:
# Create an empty error list.



# Execute a loop from 1 to 40. In each iteration calculate the mean error for predicted values of test set

#for i in range(1, 40): (uncomment this line)
    #initialize the KNN algorithm
   
    #fit the train data
    
    #make predictions
    
    #append the result to the error list.
   

In [ ]:
# plot the error values against K values. Establish the graph size.

# your code

# title and labels (uncomment the following code lines)
#plt.title('Error Rate K Value')
#plt.xlabel('K Value')
#plt.ylabel('Mean Error')

Source:

https://www.geeksforgeeks.org/

https://stackabuse.com/big-o-notation-and-algorithm-analysis-with-python-examples/

https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/

https://www.geeksforgeeks.org/selection-sort/